image: mpievolbioscicomp/repinpop_base

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
      - export
      - ./build.sh
  artifacts:
    paths:
      - REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar
      - build

test:unittest:
  stage: test
  allow_failure: true
  script:
    - source /root/.bashrc
    - conda activate repinpop
    - conda install pytest
    - source setenv.sh
    - cd test/unittest
    - pytest test_routes.py

test:neisseria:small:
  stage: test
  allow_failure: true
  script:
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./test.sh neisseria_small clean setup run_java test_java run_andi test_andi run_clustdist test_clustdist 
    - mv /tmp/rarefan_test/neisseria_small/out ../data/neisseria_small/out
  artifacts:
    paths:
      - test/data/neisseria_small/out

test:dokdonia:
  stage: test
  allow_failure: true
  script: 
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./dl_zenodo.sh dokdonia
    - ./test.sh dokdonia clean setup run_java test_java run_andi test_andi run_clustdist test_clustdist 
    - mv /tmp/rarefan_test/dokdonia/out ../data/dokdonia/out
  artifacts:
    paths:
      - test/data/dokdonia/out

test:neisseria:
  stage: test
  allow_failure: true
  script: 
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./dl_zenodo.sh neisseria
    - ./test.sh neisseria clean setup ref_plots test_ref_plots
    - mv /tmp/rarefan_test/neisseria/ref ../data/datasets/neisseria/ref
  artifacts:
    paths:
      - test/data/datasets/neisseria/ref

test:chlororaphis:
  stage: test
  allow_failure: true
  script: 
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./dl_zenodo.sh chlororaphis
    - ./test.sh chlororaphis clean setup ref_plots test_ref_plots
    - mv /tmp/rarefan_test/chlororaphis/ref ../data/datasets/chlororaphis/ref
  artifacts:
    paths:
      - test/data/datasets/chlororaphis/ref

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir pkg-dist
    - cp REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar pkg-dist
    - cp app/utilities/checkers.py pkg-dist
    - cp app/utilities/rarefan_cli.py pkg-dist/rarefan
    - chmod 755 pkg-dist/rarefan
    - cd pkg-dist
    - zip ../rarefan.zip *.jar *.py rarefan 
    - tar czvf ../rarefan.tar.gz *.jar *.py rarefan

  artifacts:
    paths:
      - rarefan.zip
      - rarefan.tar.gz

release_tag:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: deploy
      artifacts: true
  script:
    - CI/push_to_OC.sh rarefan.zip rarefan-${CI_COMMIT_TAG}.zip
    - CI/push_to_OC.sh rarefan.tar.gz rarefan-${CI_COMMIT_TAG}.tar.gz
  release:
    name: 'Tagged Release $CI_COMMIT_TAG'
    description: 'Created by gitlab CI'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_REF_NAME'

release_commit:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: deploy
      artifacts: true
  script:
    - echo "Pushing to OC."
    - CI/push_to_OC.sh rarefan.zip rarefan-${CI_COMMIT_SHORT_SHA}.zip
    - CI/push_to_OC.sh rarefan.tar.gz rarefan-${CI_COMMIT_SHORT_SHA}.tar.gz
  release:
    name: 'Nightly Release $CI_COMMIT_SHORT_SHA'
    description: 'Created by gitlab CI'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    ref: '$CI_COMMIT_REF_NAME'
