image: mpievolbioscicomp/repinpop

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - conda init bash
  - source ~/.bashrc
  - conda activate repinpop
  - lscpu
  - lsmem

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - /usr/local/envs/repinpop
      - REPIN_ecology/REPIN_ecology/build

build:
  stage: build
  script:
    - export INSTALL_PREFIX=$(echo $CONDA_PREFIX)
    - mkdir build
    - cd build
    - CC=/usr/bin/gcc cmake -D-DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
    - conda deactivate
    - conda deactivate
    - make
    - conda activate repinpop
    - cd ..
    - cd REPIN_ecology/REPIN_ecology 
    - gradle build
    - cd ../..

test:
  stage: test
  script: 
    - ./run_test.sh -d neisseria_small
