image: mpievolbioscicomp/repinpop_base

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
      - CI/build.sh
      - source ~/.bashrc
      - conda activate repinpop
      - touch __init__.py
      - ./pkg-build.sh
  artifacts:
    paths:
      - REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar
      - pkg-dist/rarefan
      - build

test:unittest:
  stage: test
  allow_failure: true
  script:
    - source /root/.bashrc
    - conda activate repinpop
    - conda install pytest
    - source setenv.sh
    - cd test/unittest
    - pytest test_routes.py

test:neisseria:small:
  stage: test
  allow_failure: true
  script:
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./test.sh neisseria_small clean setup run_java test_java run_andi test_andi run_clustdist test_clustdist 
    - mv /tmp/rarefan_test/neisseria_small/out ../data/neisseria_small/out
  artifacts:
    paths:
      - test/data/neisseria_small/out

test:dokdonia:
  stage: test
  allow_failure: true
  script: 
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./dl_zenodo.sh dokdonia
    - ./test.sh dokdonia clean setup run_java test_java run_andi test_andi run_clustdist test_clustdist 
    - mv /tmp/rarefan_test/dokdonia/out ../data/dokdonia/out
  artifacts:
    paths:
      - test/data/dokdonia/out

test:neisseria:
  stage: test
  allow_failure: true
  script: 
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./dl_zenodo.sh neisseria
    - ./test.sh neisseria clean setup ref_plots test_ref_plots
    - mv /tmp/rarefan_test/neisseria/ref ../data/datasets/neisseria/ref
  artifacts:
    paths:
      - test/data/datasets/neisseria/ref

test:chlororaphis:
  stage: test
  allow_failure: true
  script: 
    - cd build
    - make 
    - cd ..
    - source /root/.bashrc
    - conda activate repinpop
    - source setenv.sh
    - cd test/scripts
    - ./dl_zenodo.sh chlororaphis
    - ./test.sh chlororaphis clean setup ref_plots test_ref_plots
    - mv /tmp/rarefan_test/chlororaphis/ref ../data/datasets/chlororaphis/ref
  artifacts:
    paths:
      - test/data/datasets/chlororaphis/ref

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - zip rarefan.zip -r pkg-dist/rarefan
    - tar czf rarefan.tar.gz pkg-dist/rarefan
  artifacts:
    paths:
      - rarefan.zip
      - rarefan.tar.gz

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - deploy
  script:
    - echo "Make release."
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created by gitlab CI'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
