image: mpievolbioscicomp/repinpop_base

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
      - CI/build.sh
  artifacts:
    paths:
      - REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar
      - build/

test:
  stage: test
  script: 
    - CI/test.sh
  artifacts:
    paths:
      - test/data/neisseria_small/out
      - test/data/dokdonia/out
      
