name: repinpop
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - libstdcxx-ng
  - openjdk>=11.0.8
  - cmake>=3.12
  - blast=2.10
  - mcl=14.137
  - gsl>=2.4
  - flask
  - wtforms
  - gradle
  - biopython
  - email_validator
  - phyml
  - pip
  - pip:
      - flask-pymongo
      - flask-mongoengine
      - flask-wtf
      - flask-autoindex
      - flask-mail
