name: repinpop
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - ipywidgets>=7.5
  - openjdk=11.0.8
  - jupyter=1.0.0
  - voila=0.1.21
  - cmake>=3.12
  - blast=2.10
  - mcl=14.137
  - gsl>=2.4
