name: repinpop
channels:
  - conda-forge
  - defaults
  - bioconda
  - anaconda
dependencies:
  - libstdcxx-ng
  - openjdk>=11.0.8
  - cmake>=3.12
  - blast=2.10
  - mcl=14.137
  - gsl>=2.4
  - flask
  - wtforms
  - r-ggpmisc
  - r-dplyr
  - r-stringr
  - r-cowplot
  - r-ggplot2
  - r-rlang>=0.4.10
  - r-vctrs>=0.3.7
  - r-lifecycle>=1.0.0
  - r-shiny
  - r-plotly
  - r-logging
  - r-ggpubr
  - bioconductor-ggtree
  - bioconductor-muscle
  - bioconductor-biostrings
  - gradle
  - biopython
  - email_validator
  - phyml
  - pip
  - pip:
      - flask-pymongo
      - flask-wtf
      - flask-autoindex
