# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Rarefan CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    container: mpievolbioscicomp/repinpop_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          source ./build.sh
        shell: bash
      - name: zip
        run: |
          mkdir rarefan
          cp REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar rarefan
          cp app/utilities/checkers.py rarefan
          cp app/utilities/rarefan_cli.py rarefan/rarefan
          chmod 755 rarefan/rarefan
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rarefan
          path: |
            build
            rarefan
            REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar

  test:
    needs: build

    runs-on: [ubuntu-latest]
    container: mpievolbioscicomp/repinpop_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rarefan

      - name: setup rte
        run: |
          apt install andi
          ls -lrt
          cd build
          make
          cd ..
      - name: test
        run: |
          conda activate repinpop
          conda install pytest 
          source setenv.sh
          mv __w/rarefan/rarefan/rarefan ./rte
          cd rte
          chmod u+x rarefan
          ls -lrt
          ./rarefan ../test/data/neisseria_small -q ../test/data/yafM_Ecoli.faa -r Nmen_2594.fas -o /tmp/rarefan_out
        shell: bash
