# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Rarefan CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    container: mpievolbioscicomp/repinpop_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          source ./build.sh
        shell: bash
      - name: zip
        run: |
          mkdir rarefan
          cp REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar rarefan
          cp app/utilities/checkers.py rarefan
          cp app/utilities/rarefan_cli.py rarefan/rarefan
          chmod 755 rarefan/rarefan
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rarefan
          path: |
            REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar
            rarefan

  test:
    needs: build

    runs-on: [ubuntu-latest]

    container: mpievolbioscicomp/repinpop_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rarefan
      - name: setup RTE
        run: |
          source ~/.bashrc
          conda activate repinpop
          conda install pytest
          source setenv.sh
      - name: unittest
        run: |
          cd test/unittest
          pytest test_routes.py
        shell: bash

      - name: neisseria_small
        run: |
          cd test/scripts
          ./test.sh neisseria_small clean setup run_java test_java run_andi test_andi run_clustdist test_clustdist




