# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    container: mpievolbioscicomp/repinpop_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          source ./build.sh
        shell: bash
      - name: zip
        run: |
          mkdir pkg-dist
          cp REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar pkg-dist
          cp app/utilities/checkers.py pkg-dist
          cp app/utilities/rarefan_cli.py pkg-dist/rarefan
          chmod 755 pkg-dist/rarefan
          cd pkg-dist
          zip ../rarefan.zip *.jar *.py rarefan
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zip
          path: rarefan.zip
