# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Rarefan CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    container: mpievolbioscicomp/repinpop_base
    steps:
      - name: context
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          source ./build.sh
        shell: bash
      - name: zip
        run: |
          mkdir rarefan
          cp REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar rarefan
          cp app/utilities/checkers.py rarefan
          cp app/utilities/rarefan_cli.py rarefan/rarefan
          chmod 755 rarefan/rarefan
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rarefan
          path: |
            build
            rarefan
            REPIN_ecology/REPIN_ecology/build/libs/REPIN_ecology.jar

  test_linux:
    needs: build

    runs-on: ["ubuntu-latest"]
    container: mpievolbioscicomp/repinpop_base
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rarefan

      - name: setup rte
        run: |
          apt install andi
          cd build
          make clustdist patch_blast link_lapack
          cd ..
          source activate repinpop
          conda install pytest 
        shell: bash
      - name: test
        run: |
          source activate repinpop
          cd rarefan
          chmod u+x rarefan
          ./rarefan ../test/data/neisseria_small -q ../test/data/NMAA_0235.faa -r Nmen_2594.fas -o /tmp/rarefan_out | tee log
          if [ $(grep -c "^15 RAYTs" log) -ne 1 ]; then exit 1; fi 
          if [ $(grep -c "^184 21bp long sequences" log) -ne 1 ]; then exit 1; fi 
          if [ $(grep -c "^48 REPINs" log) -ne 1 ]; then exit 1; fi 

          echo "====> Test passed <===="
          exit 0
        shell: bash

  test_mac:
    needs: build

    runs-on: ["macos-latest"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rarefan

      - name: "setup conda"
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true

      - name: "install mcl"
        run: |
          conda install mcl blast andi -c bioconda
          patch /usr/local/miniconda/bin/legacy_blast.pl patch

      - name: "install clustdist"
        run: |
          cd build
          make clustdist
          cd ..

      - name: test
        run: |
          cd rarefan
          chmod u+x rarefan
          ./rarefan ../test/data/neisseria_small -q ../test/data/NMAA_0235.faa -r Nmen_2594.fas -o /tmp/rarefan_out | tee log
          if [ $(grep -c "^15 RAYTs" log) -ne 1 ]; then exit 1; fi 
          if [ $(grep -c "^184 21bp long sequences" log) -ne 1 ]; then exit 1; fi 
          if [ $(grep -c "^48 REPINs" log) -ne 1 ]; then exit 1; fi 

          echo "====> Test passed <===="
          exit 0
        shell: bash

  release:
    needs: [test_linux, test_mac]
    runs-on: ["ubuntu-20.04"]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rarefan

      - name: pack
        run: |
          zip -r rarefan-${{github.ref_name}}.zip rarefan
        shell: bash

      - name: "Release step"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.ref_name}}"
          title: "RAREFAN ${{ github.ref_name}}"
          files: |
            LICENSE
            rarefan-${{github.ref_name}}.zip
